
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20140611 (SVN rev 31)
// Sun Mar 15 14:20:13 CST 2015
//----------------------------------------------------

package hashtag;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int NUMERO = 47;
  public static final int DOSPUNTOS = 20;
  public static final int FUNCTION = 32;
  public static final int MULT = 5;
  public static final int CHAR = 38;
  public static final int READINT = 43;
  public static final int OTHER = 45;
  public static final int CASE = 30;
  public static final int DIFERENTE = 11;
  public static final int DOUBLE = 37;
  public static final int INT = 36;
  public static final int PUNTOCOMA = 18;
  public static final int FOR = 23;
  public static final int IDENTIFICADOR = 51;
  public static final int NOT = 10;
  public static final int MENORIGUAL = 9;
  public static final int AND = 21;
  public static final int IGUAL = 12;
  public static final int CARACTER = 49;
  public static final int OR = 22;
  public static final int DIV = 4;
  public static final int BEGIN = 27;
  public static final int SUMA = 2;
  public static final int IF = 24;
  public static final int MAYORIGUAL = 8;
  public static final int BOOLEAN = 40;
  public static final int EOF = 0;
  public static final int PARIZQ = 15;
  public static final int RETURN = 34;
  public static final int TRUE = 53;
  public static final int READSTRING = 41;
  public static final int error = 1;
  public static final int COMA = 17;
  public static final int CADENA = 50;
  public static final int MENOS = 3;
  public static final int MENOR = 7;
  public static final int MOD = 16;
  public static final int READCHAR = 42;
  public static final int BREAK = 33;
  public static final int VOID = 46;
  public static final int ASIGNACION = 13;
  public static final int SWITCH = 29;
  public static final int REAL = 48;
  public static final int MAYOR = 6;
  public static final int ELSE = 25;
  public static final int MAINBEGIN = 19;
  public static final int WHILE = 26;
  public static final int END = 28;
  public static final int STRING = 39;
  public static final int READDOUBLE = 44;
  public static final int FALSE = 52;
  public static final int PARDER = 14;
  public static final int PRINT = 35;
  public static final int DO = 31;
}

