
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20140611 (SVN rev 31)
// Thu Mar 05 21:37:53 CST 2015
//----------------------------------------------------

package hashtag;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int NUMERO = 45;
  public static final int DOSPUNTOS = 41;
  public static final int FUNCTION = 7;
  public static final int INTERROGACION = 37;
  public static final int MULT = 22;
  public static final int CHAR = 49;
  public static final int CASE = 18;
  public static final int DIFERENTE = 29;
  public static final int DOUBLE = 48;
  public static final int INT = 47;
  public static final int PUNTOCOMA = 36;
  public static final int FOR = 10;
  public static final int ENDMAIN = 3;
  public static final int CORCHETEIZQ = 39;
  public static final int IDENTIFICADOR = 44;
  public static final int NOT = 30;
  public static final int MENORIGUAL = 26;
  public static final int AND = 15;
  public static final int IGUAL = 28;
  public static final int OR = 16;
  public static final int DIV = 21;
  public static final int BEGIN = 4;
  public static final int SUMA = 19;
  public static final int IF = 13;
  public static final int MAYORIGUAL = 27;
  public static final int BOOLEAN = 51;
  public static final int EOF = 0;
  public static final int PARIZQ = 33;
  public static final int RETURN = 8;
  public static final int UNACOMILLA = 38;
  public static final int TRUE = 31;
  public static final int error = 1;
  public static final int COMA = 35;
  public static final int MENOS = 20;
  public static final int MENOR = 25;
  public static final int MOD = 23;
  public static final int BREAK = 12;
  public static final int ASIGNACION = 42;
  public static final int SWITCH = 17;
  public static final int REAL = 46;
  public static final int MAYOR = 24;
  public static final int CORCHETEDER = 40;
  public static final int ELSE = 14;
  public static final int PUNTO = 43;
  public static final int MAINBEGIN = 2;
  public static final int WHILE = 11;
  public static final int END = 6;
  public static final int STRING = 50;
  public static final int FALSE = 32;
  public static final int PARDER = 34;
  public static final int PRINT = 9;
  public static final int DO = 5;
}

