
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20140611 (SVN rev 31)
// Wed Mar 11 19:57:25 CST 2015
//----------------------------------------------------

package hashtag;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int NUMERO = 47;
  public static final int DOSPUNTOS = 27;
  public static final int FUNCTION = 43;
  public static final int INTERROGACION = 22;
  public static final int MULT = 5;
  public static final int CHAR = 58;
  public static final int READINT = 53;
  public static final int OTHER = 55;
  public static final int CASE = 39;
  public static final int DIFERENTE = 11;
  public static final int DOUBLE = 57;
  public static final int INT = 56;
  public static final int PUNTOCOMA = 20;
  public static final int ENDMAIN = 37;
  public static final int FOR = 30;
  public static final int CORCHETEIZQ = 25;
  public static final int IDENTIFICADOR = 15;
  public static final int NOT = 10;
  public static final int MENORIGUAL = 9;
  public static final int AND = 28;
  public static final int IGUAL = 12;
  public static final int CARACTER = 50;
  public static final int OR = 29;
  public static final int BEGIN = 35;
  public static final int DIV = 4;
  public static final int SUMA = 2;
  public static final int IF = 31;
  public static final int MAYORIGUAL = 8;
  public static final int BOOLEAN = 60;
  public static final int EOF = 0;
  public static final int PARIZQ = 17;
  public static final int RETURN = 45;
  public static final int TRUE = 41;
  public static final int UNACOMILLA = 23;
  public static final int COMILLAS = 21;
  public static final int READSTRING = 51;
  public static final int error = 1;
  public static final int COMA = 19;
  public static final int CADENA = 49;
  public static final int MENOS = 3;
  public static final int MENOR = 7;
  public static final int MOD = 18;
  public static final int READCHAR = 52;
  public static final int BREAK = 44;
  public static final int SWITCH = 38;
  public static final int ASIGNACION = 13;
  public static final int REAL = 48;
  public static final int MAYOR = 6;
  public static final int CORCHETEDER = 24;
  public static final int ELSE = 33;
  public static final int PUNTO = 14;
  public static final int MAINBEGIN = 26;
  public static final int WHILE = 34;
  public static final int THEN = 32;
  public static final int END = 36;
  public static final int STRING = 59;
  public static final int READDOUBLE = 54;
  public static final int FALSE = 42;
  public static final int PARDER = 16;
  public static final int PRINT = 46;
  public static final int DO = 40;
}

